export const AboutAgency = () => import('../..\\components\\AboutAgency.vue' /* webpackChunkName: "components/about-agency" */).then(c => wrapFunctional(c.default || c))
export const AboutAuthenticStudio = () => import('../..\\components\\AboutAuthenticStudio.vue' /* webpackChunkName: "components/about-authentic-studio" */).then(c => wrapFunctional(c.default || c))
export const AboutBreadcrumb = () => import('../..\\components\\AboutBreadcrumb.vue' /* webpackChunkName: "components/about-breadcrumb" */).then(c => wrapFunctional(c.default || c))
export const AboutBreadcrumbFour = () => import('../..\\components\\AboutBreadcrumbFour.vue' /* webpackChunkName: "components/about-breadcrumb-four" */).then(c => wrapFunctional(c.default || c))
export const AboutBreadcrumbThree = () => import('../..\\components\\AboutBreadcrumbThree.vue' /* webpackChunkName: "components/about-breadcrumb-three" */).then(c => wrapFunctional(c.default || c))
export const AboutSkill = () => import('../..\\components\\AboutSkill.vue' /* webpackChunkName: "components/about-skill" */).then(c => wrapFunctional(c.default || c))
export const AccordionStyleOne = () => import('../..\\components\\AccordionStyleOne.vue' /* webpackChunkName: "components/accordion-style-one" */).then(c => wrapFunctional(c.default || c))
export const AccordionStyleTwo = () => import('../..\\components\\AccordionStyleTwo.vue' /* webpackChunkName: "components/accordion-style-two" */).then(c => wrapFunctional(c.default || c))
export const AgencyCounterup = () => import('../..\\components\\AgencyCounterup.vue' /* webpackChunkName: "components/agency-counterup" */).then(c => wrapFunctional(c.default || c))
export const AlbumList = () => import('../..\\components\\AlbumList.vue' /* webpackChunkName: "components/album-list" */).then(c => wrapFunctional(c.default || c))
export const BestService = () => import('../..\\components\\BestService.vue' /* webpackChunkName: "components/best-service" */).then(c => wrapFunctional(c.default || c))
export const BlogPost = () => import('../..\\components\\BlogPost.vue' /* webpackChunkName: "components/blog-post" */).then(c => wrapFunctional(c.default || c))
export const BlogPostFour = () => import('../..\\components\\BlogPostFour.vue' /* webpackChunkName: "components/blog-post-four" */).then(c => wrapFunctional(c.default || c))
export const BlogPostThree = () => import('../..\\components\\BlogPostThree.vue' /* webpackChunkName: "components/blog-post-three" */).then(c => wrapFunctional(c.default || c))
export const BlogPostTwo = () => import('../..\\components\\BlogPostTwo.vue' /* webpackChunkName: "components/blog-post-two" */).then(c => wrapFunctional(c.default || c))
export const BlogRestaurant = () => import('../..\\components\\BlogRestaurant.vue' /* webpackChunkName: "components/blog-restaurant" */).then(c => wrapFunctional(c.default || c))
export const BlogSidebar = () => import('../..\\components\\BlogSidebar.vue' /* webpackChunkName: "components/blog-sidebar" */).then(c => wrapFunctional(c.default || c))
export const BrandLogoCarousel = () => import('../..\\components\\BrandLogoCarousel.vue' /* webpackChunkName: "components/brand-logo-carousel" */).then(c => wrapFunctional(c.default || c))
export const BrandLogoCarouselCustom = () => import('../..\\components\\BrandLogoCarouselCustom.vue' /* webpackChunkName: "components/brand-logo-carousel-custom" */).then(c => wrapFunctional(c.default || c))
export const BrandLogoCarouselWithNavigation = () => import('../..\\components\\BrandLogoCarouselWithNavigation.vue' /* webpackChunkName: "components/brand-logo-carousel-with-navigation" */).then(c => wrapFunctional(c.default || c))
export const BrandLogoStyleOne = () => import('../..\\components\\BrandLogoStyleOne.vue' /* webpackChunkName: "components/brand-logo-style-one" */).then(c => wrapFunctional(c.default || c))
export const BrandLogoWithoutCarousel = () => import('../..\\components\\BrandLogoWithoutCarousel.vue' /* webpackChunkName: "components/brand-logo-without-carousel" */).then(c => wrapFunctional(c.default || c))
export const Breadcrumb = () => import('../..\\components\\Breadcrumb.vue' /* webpackChunkName: "components/breadcrumb" */).then(c => wrapFunctional(c.default || c))
export const CallToAction = () => import('../..\\components\\CallToAction.vue' /* webpackChunkName: "components/call-to-action" */).then(c => wrapFunctional(c.default || c))
export const CareerItem = () => import('../..\\components\\CareerItem.vue' /* webpackChunkName: "components/career-item" */).then(c => wrapFunctional(c.default || c))
export const ContactForm = () => import('../..\\components\\ContactForm.vue' /* webpackChunkName: "components/contact-form" */).then(c => wrapFunctional(c.default || c))
export const ContactUsBreadcrumb = () => import('../..\\components\\ContactUsBreadcrumb.vue' /* webpackChunkName: "components/contact-us-breadcrumb" */).then(c => wrapFunctional(c.default || c))
export const ContactUsOne = () => import('../..\\components\\ContactUsOne.vue' /* webpackChunkName: "components/contact-us-one" */).then(c => wrapFunctional(c.default || c))
export const ContactUsThree = () => import('../..\\components\\ContactUsThree.vue' /* webpackChunkName: "components/contact-us-three" */).then(c => wrapFunctional(c.default || c))
export const ContactUsTwo = () => import('../..\\components\\ContactUsTwo.vue' /* webpackChunkName: "components/contact-us-two" */).then(c => wrapFunctional(c.default || c))
export const CurveShape = () => import('../..\\components\\CurveShape.vue' /* webpackChunkName: "components/curve-shape" */).then(c => wrapFunctional(c.default || c))
export const EffectiveSolution = () => import('../..\\components\\EffectiveSolution.vue' /* webpackChunkName: "components/effective-solution" */).then(c => wrapFunctional(c.default || c))
export const EssentialCaseStudy = () => import('../..\\components\\EssentialCaseStudy.vue' /* webpackChunkName: "components/essential-case-study" */).then(c => wrapFunctional(c.default || c))
export const EssentialIconBox = () => import('../..\\components\\EssentialIconBox.vue' /* webpackChunkName: "components/essential-icon-box" */).then(c => wrapFunctional(c.default || c))
export const EssentialService = () => import('../..\\components\\EssentialService.vue' /* webpackChunkName: "components/essential-service" */).then(c => wrapFunctional(c.default || c))
export const EssentialSkillProgress = () => import('../..\\components\\EssentialSkillProgress.vue' /* webpackChunkName: "components/essential-skill-progress" */).then(c => wrapFunctional(c.default || c))
export const EssentialTestimonial = () => import('../..\\components\\EssentialTestimonial.vue' /* webpackChunkName: "components/essential-testimonial" */).then(c => wrapFunctional(c.default || c))
export const FeaturedProjects = () => import('../..\\components\\FeaturedProjects.vue' /* webpackChunkName: "components/featured-projects" */).then(c => wrapFunctional(c.default || c))
export const FeatureItemStyleOne = () => import('../..\\components\\FeatureItemStyleOne.vue' /* webpackChunkName: "components/feature-item-style-one" */).then(c => wrapFunctional(c.default || c))
export const Firefly = () => import('../..\\components\\Firefly.vue' /* webpackChunkName: "components/firefly" */).then(c => wrapFunctional(c.default || c))
export const FlexibleSlider = () => import('../..\\components\\FlexibleSlider.vue' /* webpackChunkName: "components/flexible-slider" */).then(c => wrapFunctional(c.default || c))
export const FlexibleSliderFive = () => import('../..\\components\\FlexibleSliderFive.vue' /* webpackChunkName: "components/flexible-slider-five" */).then(c => wrapFunctional(c.default || c))
export const FlexibleSliderFour = () => import('../..\\components\\FlexibleSliderFour.vue' /* webpackChunkName: "components/flexible-slider-four" */).then(c => wrapFunctional(c.default || c))
export const FlexibleSliderThree = () => import('../..\\components\\FlexibleSliderThree.vue' /* webpackChunkName: "components/flexible-slider-three" */).then(c => wrapFunctional(c.default || c))
export const FlexibleSliderTwo = () => import('../..\\components\\FlexibleSliderTwo.vue' /* webpackChunkName: "components/flexible-slider-two" */).then(c => wrapFunctional(c.default || c))
export const Footer = () => import('../..\\components\\Footer.vue' /* webpackChunkName: "components/footer" */).then(c => wrapFunctional(c.default || c))
export const FooterAgency = () => import('../..\\components\\FooterAgency.vue' /* webpackChunkName: "components/footer-agency" */).then(c => wrapFunctional(c.default || c))
export const FooterStyleFour = () => import('../..\\components\\FooterStyleFour.vue' /* webpackChunkName: "components/footer-style-four" */).then(c => wrapFunctional(c.default || c))
export const FooterStyleThree = () => import('../..\\components\\FooterStyleThree.vue' /* webpackChunkName: "components/footer-style-three" */).then(c => wrapFunctional(c.default || c))
export const FooterTwo = () => import('../..\\components\\FooterTwo.vue' /* webpackChunkName: "components/footer-two" */).then(c => wrapFunctional(c.default || c))
export const GoogleMap = () => import('../..\\components\\GoogleMap.vue' /* webpackChunkName: "components/google-map" */).then(c => wrapFunctional(c.default || c))
export const GradationOne = () => import('../..\\components\\GradationOne.vue' /* webpackChunkName: "components/gradation-one" */).then(c => wrapFunctional(c.default || c))
export const Header = () => import('../..\\components\\Header.vue' /* webpackChunkName: "components/header" */).then(c => wrapFunctional(c.default || c))
export const HeaderAbout = () => import('../..\\components\\HeaderAbout.vue' /* webpackChunkName: "components/header-about" */).then(c => wrapFunctional(c.default || c))
export const HeaderBlack = () => import('../..\\components\\HeaderBlack.vue' /* webpackChunkName: "components/header-black" */).then(c => wrapFunctional(c.default || c))
export const HeaderBlackTransparentWithSocial = () => import('../..\\components\\HeaderBlackTransparentWithSocial.vue' /* webpackChunkName: "components/header-black-transparent-with-social" */).then(c => wrapFunctional(c.default || c))
export const HeaderElement = () => import('../..\\components\\HeaderElement.vue' /* webpackChunkName: "components/header-element" */).then(c => wrapFunctional(c.default || c))
export const HeaderForOffCanvas = () => import('../..\\components\\HeaderForOffCanvas.vue' /* webpackChunkName: "components/header-for-off-canvas" */).then(c => wrapFunctional(c.default || c))
export const HeaderForOffCanvasBlack = () => import('../..\\components\\HeaderForOffCanvasBlack.vue' /* webpackChunkName: "components/header-for-off-canvas-black" */).then(c => wrapFunctional(c.default || c))
export const HeaderOnepage = () => import('../..\\components\\HeaderOnepage.vue' /* webpackChunkName: "components/header-onepage" */).then(c => wrapFunctional(c.default || c))
export const HeaderPortfolioSlider = () => import('../..\\components\\HeaderPortfolioSlider.vue' /* webpackChunkName: "components/header-portfolio-slider" */).then(c => wrapFunctional(c.default || c))
export const HeaderTransparentWithSocial = () => import('../..\\components\\HeaderTransparentWithSocial.vue' /* webpackChunkName: "components/header-transparent-with-social" */).then(c => wrapFunctional(c.default || c))
export const HeaderVerticalOffcanvas = () => import('../..\\components\\HeaderVerticalOffcanvas.vue' /* webpackChunkName: "components/header-vertical-offcanvas" */).then(c => wrapFunctional(c.default || c))
export const HeaderVerticalRestaurant = () => import('../..\\components\\HeaderVerticalRestaurant.vue' /* webpackChunkName: "components/header-vertical-restaurant" */).then(c => wrapFunctional(c.default || c))
export const HeaderVerticle = () => import('../..\\components\\HeaderVerticle.vue' /* webpackChunkName: "components/header-verticle" */).then(c => wrapFunctional(c.default || c))
export const HeroAgency = () => import('../..\\components\\HeroAgency.vue' /* webpackChunkName: "components/hero-agency" */).then(c => wrapFunctional(c.default || c))
export const HeroAuthenticStudio = () => import('../..\\components\\HeroAuthenticStudio.vue' /* webpackChunkName: "components/hero-authentic-studio" */).then(c => wrapFunctional(c.default || c))
export const HeroBusiness = () => import('../..\\components\\HeroBusiness.vue' /* webpackChunkName: "components/hero-business" */).then(c => wrapFunctional(c.default || c))
export const HeroDesignStudio = () => import('../..\\components\\HeroDesignStudio.vue' /* webpackChunkName: "components/hero-design-studio" */).then(c => wrapFunctional(c.default || c))
export const HeroDigitalAgency = () => import('../..\\components\\HeroDigitalAgency.vue' /* webpackChunkName: "components/hero-digital-agency" */).then(c => wrapFunctional(c.default || c))
export const HeroEssential = () => import('../..\\components\\HeroEssential.vue' /* webpackChunkName: "components/hero-essential" */).then(c => wrapFunctional(c.default || c))
export const HeroFullscreen = () => import('../..\\components\\HeroFullscreen.vue' /* webpackChunkName: "components/hero-fullscreen" */).then(c => wrapFunctional(c.default || c))
export const HeroIndieMusician = () => import('../..\\components\\HeroIndieMusician.vue' /* webpackChunkName: "components/hero-indie-musician" */).then(c => wrapFunctional(c.default || c))
export const HeroLanding = () => import('../..\\components\\HeroLanding.vue' /* webpackChunkName: "components/hero-landing" */).then(c => wrapFunctional(c.default || c))
export const HeroMinimalAgency = () => import('../..\\components\\HeroMinimalAgency.vue' /* webpackChunkName: "components/hero-minimal-agency" */).then(c => wrapFunctional(c.default || c))
export const HeroOnepage = () => import('../..\\components\\HeroOnepage.vue' /* webpackChunkName: "components/hero-onepage" */).then(c => wrapFunctional(c.default || c))
export const HeroPhotoSliderGallery = () => import('../..\\components\\HeroPhotoSliderGallery.vue' /* webpackChunkName: "components/hero-photo-slider-gallery" */).then(c => wrapFunctional(c.default || c))
export const HeroPortfolioSlide = () => import('../..\\components\\HeroPortfolioSlide.vue' /* webpackChunkName: "components/hero-portfolio-slide" */).then(c => wrapFunctional(c.default || c))
export const HeroProductLanding = () => import('../..\\components\\HeroProductLanding.vue' /* webpackChunkName: "components/hero-product-landing" */).then(c => wrapFunctional(c.default || c))
export const HeroRestaurant = () => import('../..\\components\\HeroRestaurant.vue' /* webpackChunkName: "components/hero-restaurant" */).then(c => wrapFunctional(c.default || c))
export const HeroService = () => import('../..\\components\\HeroService.vue' /* webpackChunkName: "components/hero-service" */).then(c => wrapFunctional(c.default || c))
export const HeroStartUp = () => import('../..\\components\\HeroStartUp.vue' /* webpackChunkName: "components/hero-start-up" */).then(c => wrapFunctional(c.default || c))
export const HeroVertical = () => import('../..\\components\\HeroVertical.vue' /* webpackChunkName: "components/hero-vertical" */).then(c => wrapFunctional(c.default || c))
export const IconBoxItemOne = () => import('../..\\components\\IconBoxItemOne.vue' /* webpackChunkName: "components/icon-box-item-one" */).then(c => wrapFunctional(c.default || c))
export const InstagramPost = () => import('../..\\components\\InstagramPost.vue' /* webpackChunkName: "components/instagram-post" */).then(c => wrapFunctional(c.default || c))
export const MinimalMetroGrid = () => import('../..\\components\\MinimalMetroGrid.vue' /* webpackChunkName: "components/minimal-metro-grid" */).then(c => wrapFunctional(c.default || c))
export const MobileNavigation = () => import('../..\\components\\MobileNavigation.vue' /* webpackChunkName: "components/mobile-navigation" */).then(c => wrapFunctional(c.default || c))
export const MotivationalArchive = () => import('../..\\components\\MotivationalArchive.vue' /* webpackChunkName: "components/motivational-archive" */).then(c => wrapFunctional(c.default || c))
export const MusicianBlog = () => import('../..\\components\\MusicianBlog.vue' /* webpackChunkName: "components/musician-blog" */).then(c => wrapFunctional(c.default || c))
export const MusicianCountdown = () => import('../..\\components\\MusicianCountdown.vue' /* webpackChunkName: "components/musician-countdown" */).then(c => wrapFunctional(c.default || c))
export const MusicianCounterup = () => import('../..\\components\\MusicianCounterup.vue' /* webpackChunkName: "components/musician-counterup" */).then(c => wrapFunctional(c.default || c))
export const MusicianGallery = () => import('../..\\components\\MusicianGallery.vue' /* webpackChunkName: "components/musician-gallery" */).then(c => wrapFunctional(c.default || c))
export const MusicianIconBox = () => import('../..\\components\\MusicianIconBox.vue' /* webpackChunkName: "components/musician-icon-box" */).then(c => wrapFunctional(c.default || c))
export const MusicianMixTapes = () => import('../..\\components\\MusicianMixTapes.vue' /* webpackChunkName: "components/musician-mix-tapes" */).then(c => wrapFunctional(c.default || c))
export const MusicianPortfolioGallery = () => import('../..\\components\\MusicianPortfolioGallery.vue' /* webpackChunkName: "components/musician-portfolio-gallery" */).then(c => wrapFunctional(c.default || c))
export const Navigation = () => import('../..\\components\\Navigation.vue' /* webpackChunkName: "components/navigation" */).then(c => wrapFunctional(c.default || c))
export const NewsletterCta = () => import('../..\\components\\NewsletterCta.vue' /* webpackChunkName: "components/newsletter-cta" */).then(c => wrapFunctional(c.default || c))
export const OffcanvasMenu = () => import('../..\\components\\OffcanvasMenu.vue' /* webpackChunkName: "components/offcanvas-menu" */).then(c => wrapFunctional(c.default || c))
export const OffCanvasMobileMenu = () => import('../..\\components\\OffCanvasMobileMenu.vue' /* webpackChunkName: "components/off-canvas-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const OnepageTeammember = () => import('../..\\components\\OnepageTeammember.vue' /* webpackChunkName: "components/onepage-teammember" */).then(c => wrapFunctional(c.default || c))
export const PortfolioItemCaptionBottom = () => import('../..\\components\\PortfolioItemCaptionBottom.vue' /* webpackChunkName: "components/portfolio-item-caption-bottom" */).then(c => wrapFunctional(c.default || c))
export const PortfolioItemCenterCaption = () => import('../..\\components\\PortfolioItemCenterCaption.vue' /* webpackChunkName: "components/portfolio-item-center-caption" */).then(c => wrapFunctional(c.default || c))
export const PricingItemStyleOne = () => import('../..\\components\\PricingItemStyleOne.vue' /* webpackChunkName: "components/pricing-item-style-one" */).then(c => wrapFunctional(c.default || c))
export const PricingItemStyleTwo = () => import('../..\\components\\PricingItemStyleTwo.vue' /* webpackChunkName: "components/pricing-item-style-two" */).then(c => wrapFunctional(c.default || c))
export const ProductTab = () => import('../..\\components\\ProductTab.vue' /* webpackChunkName: "components/product-tab" */).then(c => wrapFunctional(c.default || c))
export const SearchPopup = () => import('../..\\components\\SearchPopup.vue' /* webpackChunkName: "components/search-popup" */).then(c => wrapFunctional(c.default || c))
export const ServiceAgency = () => import('../..\\components\\ServiceAgency.vue' /* webpackChunkName: "components/service-agency" */).then(c => wrapFunctional(c.default || c))
export const ServiceClassicBreadcrumb = () => import('../..\\components\\ServiceClassicBreadcrumb.vue' /* webpackChunkName: "components/service-classic-breadcrumb" */).then(c => wrapFunctional(c.default || c))
export const ServiceItemOne = () => import('../..\\components\\ServiceItemOne.vue' /* webpackChunkName: "components/service-item-one" */).then(c => wrapFunctional(c.default || c))
export const ServiceItemOneWithoutButton = () => import('../..\\components\\ServiceItemOneWithoutButton.vue' /* webpackChunkName: "components/service-item-one-without-button" */).then(c => wrapFunctional(c.default || c))
export const ServiceItemStyleTwo = () => import('../..\\components\\ServiceItemStyleTwo.vue' /* webpackChunkName: "components/service-item-style-two" */).then(c => wrapFunctional(c.default || c))
export const ServiceModern = () => import('../..\\components\\ServiceModern.vue' /* webpackChunkName: "components/service-modern" */).then(c => wrapFunctional(c.default || c))
export const ServiceModernBreadcrumb = () => import('../..\\components\\ServiceModernBreadcrumb.vue' /* webpackChunkName: "components/service-modern-breadcrumb" */).then(c => wrapFunctional(c.default || c))
export const TabOne = () => import('../..\\components\\TabOne.vue' /* webpackChunkName: "components/tab-one" */).then(c => wrapFunctional(c.default || c))
export const TabVertical = () => import('../..\\components\\TabVertical.vue' /* webpackChunkName: "components/tab-vertical" */).then(c => wrapFunctional(c.default || c))
export const TeamCarouselFull = () => import('../..\\components\\TeamCarouselFull.vue' /* webpackChunkName: "components/team-carousel-full" */).then(c => wrapFunctional(c.default || c))
export const TeamMemberOne = () => import('../..\\components\\TeamMemberOne.vue' /* webpackChunkName: "components/team-member-one" */).then(c => wrapFunctional(c.default || c))
export const TeamMemberThree = () => import('../..\\components\\TeamMemberThree.vue' /* webpackChunkName: "components/team-member-three" */).then(c => wrapFunctional(c.default || c))
export const TeamMemberTwo = () => import('../..\\components\\TeamMemberTwo.vue' /* webpackChunkName: "components/team-member-two" */).then(c => wrapFunctional(c.default || c))
export const TestimonialItem = () => import('../..\\components\\TestimonialItem.vue' /* webpackChunkName: "components/testimonial-item" */).then(c => wrapFunctional(c.default || c))
export const TestimonialSix = () => import('../..\\components\\TestimonialSix.vue' /* webpackChunkName: "components/testimonial-six" */).then(c => wrapFunctional(c.default || c))
export const VideoOne = () => import('../..\\components\\VideoOne.vue' /* webpackChunkName: "components/video-one" */).then(c => wrapFunctional(c.default || c))
export const VideoService = () => import('../..\\components\\VideoService.vue' /* webpackChunkName: "components/video-service" */).then(c => wrapFunctional(c.default || c))
export const WhatWeDo = () => import('../..\\components\\WhatWeDo.vue' /* webpackChunkName: "components/what-we-do" */).then(c => wrapFunctional(c.default || c))
export const WhatWeDoTwo = () => import('../..\\components\\WhatWeDoTwo.vue' /* webpackChunkName: "components/what-we-do-two" */).then(c => wrapFunctional(c.default || c))
export const AboutServiceItemOneWithoutButton = () => import('../..\\components\\about\\ServiceItemOneWithoutButton.vue' /* webpackChunkName: "components/about-service-item-one-without-button" */).then(c => wrapFunctional(c.default || c))
export const AboutServiceTwo = () => import('../..\\components\\about\\ServiceTwo.vue' /* webpackChunkName: "components/about-service-two" */).then(c => wrapFunctional(c.default || c))
export const AboutWhatWeDoThree = () => import('../..\\components\\about\\WhatWeDoThree.vue' /* webpackChunkName: "components/about-what-we-do-three" */).then(c => wrapFunctional(c.default || c))
export const ContactMobileNavigation = () => import('../..\\components\\contact\\MobileNavigation.vue' /* webpackChunkName: "components/contact-mobile-navigation" */).then(c => wrapFunctional(c.default || c))
export const ContactNavigation = () => import('../..\\components\\contact\\Navigation.vue' /* webpackChunkName: "components/contact-navigation" */).then(c => wrapFunctional(c.default || c))
export const ContactOffcanvasMenu = () => import('../..\\components\\contact\\OffcanvasMenu.vue' /* webpackChunkName: "components/contact-offcanvas-menu" */).then(c => wrapFunctional(c.default || c))
export const ContactOffCanvasMobileMenu = () => import('../..\\components\\contact\\OffCanvasMobileMenu.vue' /* webpackChunkName: "components/contact-off-canvas-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const EventsExpandableImage = () => import('../..\\components\\events\\ExpandableImage.vue' /* webpackChunkName: "components/events-expandable-image" */).then(c => wrapFunctional(c.default || c))
export const EventsHeaderVerticle = () => import('../..\\components\\events\\HeaderVerticle.vue' /* webpackChunkName: "components/events-header-verticle" */).then(c => wrapFunctional(c.default || c))
export const EventsHeroFullscreen = () => import('../..\\components\\events\\HeroFullscreen.vue' /* webpackChunkName: "components/events-hero-fullscreen" */).then(c => wrapFunctional(c.default || c))
export const EventsMobileNavigation = () => import('../..\\components\\events\\MobileNavigation.vue' /* webpackChunkName: "components/events-mobile-navigation" */).then(c => wrapFunctional(c.default || c))
export const EventsNavigation = () => import('../..\\components\\events\\Navigation.vue' /* webpackChunkName: "components/events-navigation" */).then(c => wrapFunctional(c.default || c))
export const EventsOffCanvasMobileMenu = () => import('../..\\components\\events\\OffCanvasMobileMenu.vue' /* webpackChunkName: "components/events-off-canvas-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const LandingContactUsThree = () => import('../..\\components\\landing\\ContactUsThree.vue' /* webpackChunkName: "components/landing-contact-us-three" */).then(c => wrapFunctional(c.default || c))
export const LandingCurveShape = () => import('../..\\components\\landing\\CurveShape.vue' /* webpackChunkName: "components/landing-curve-shape" */).then(c => wrapFunctional(c.default || c))
export const LandingEssentialService = () => import('../..\\components\\landing\\EssentialService.vue' /* webpackChunkName: "components/landing-essential-service" */).then(c => wrapFunctional(c.default || c))
export const LandingEssentialTestimonial1 = () => import('../..\\components\\landing\\EssentialTestimonial1.vue' /* webpackChunkName: "components/landing-essential-testimonial1" */).then(c => wrapFunctional(c.default || c))
export const LandingEssentialTestimonial2 = () => import('../..\\components\\landing\\EssentialTestimonial2.vue' /* webpackChunkName: "components/landing-essential-testimonial2" */).then(c => wrapFunctional(c.default || c))
export const LandingEventsItemCaptionCenter = () => import('../..\\components\\landing\\EventsItemCaptionCenter.vue' /* webpackChunkName: "components/landing-events-item-caption-center" */).then(c => wrapFunctional(c.default || c))
export const LandingFlexibleSliderFour = () => import('../..\\components\\landing\\FlexibleSliderFour.vue' /* webpackChunkName: "components/landing-flexible-slider-four" */).then(c => wrapFunctional(c.default || c))
export const LandingFooterTwo = () => import('../..\\components\\landing\\FooterTwo.vue' /* webpackChunkName: "components/landing-footer-two" */).then(c => wrapFunctional(c.default || c))
export const LandingHeaderForOffCanvas = () => import('../..\\components\\landing\\HeaderForOffCanvas.vue' /* webpackChunkName: "components/landing-header-for-off-canvas" */).then(c => wrapFunctional(c.default || c))
export const LandingHeroService = () => import('../..\\components\\landing\\HeroService.vue' /* webpackChunkName: "components/landing-hero-service" */).then(c => wrapFunctional(c.default || c))
export const LandingMobileNavigation = () => import('../..\\components\\landing\\MobileNavigation.vue' /* webpackChunkName: "components/landing-mobile-navigation" */).then(c => wrapFunctional(c.default || c))
export const LandingNavigation = () => import('../..\\components\\landing\\Navigation.vue' /* webpackChunkName: "components/landing-navigation" */).then(c => wrapFunctional(c.default || c))
export const LandingOffcanvasMenu = () => import('../..\\components\\landing\\OffcanvasMenu.vue' /* webpackChunkName: "components/landing-offcanvas-menu" */).then(c => wrapFunctional(c.default || c))
export const LandingOffCanvasMobileMenu = () => import('../..\\components\\landing\\OffCanvasMobileMenu.vue' /* webpackChunkName: "components/landing-off-canvas-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const LandingPortfolioItemCenterCaption = () => import('../..\\components\\landing\\PortfolioItemCenterCaption.vue' /* webpackChunkName: "components/landing-portfolio-item-center-caption" */).then(c => wrapFunctional(c.default || c))
export const LandingPortfolioItemFilter = () => import('../..\\components\\landing\\PortfolioItemFilter.vue' /* webpackChunkName: "components/landing-portfolio-item-filter" */).then(c => wrapFunctional(c.default || c))
export const LandingServiceCarousel = () => import('../..\\components\\landing\\ServiceCarousel.vue' /* webpackChunkName: "components/landing-service-carousel" */).then(c => wrapFunctional(c.default || c))
export const SectionsAccordionOne = () => import('../..\\components\\sections\\AccordionOne.vue' /* webpackChunkName: "components/sections-accordion-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsBlogOne = () => import('../..\\components\\sections\\BlogOne.vue' /* webpackChunkName: "components/sections-blog-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsBlogThree = () => import('../..\\components\\sections\\BlogThree.vue' /* webpackChunkName: "components/sections-blog-three" */).then(c => wrapFunctional(c.default || c))
export const SectionsBlogTwo = () => import('../..\\components\\sections\\BlogTwo.vue' /* webpackChunkName: "components/sections-blog-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsCarouselWithCaptionOne = () => import('../..\\components\\sections\\CarouselWithCaptionOne.vue' /* webpackChunkName: "components/sections-carousel-with-caption-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsCarouselWithCaptionTwo = () => import('../..\\components\\sections\\CarouselWithCaptionTwo.vue' /* webpackChunkName: "components/sections-carousel-with-caption-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsContactModern = () => import('../..\\components\\sections\\ContactModern.vue' /* webpackChunkName: "components/sections-contact-modern" */).then(c => wrapFunctional(c.default || c))
export const SectionsCounterUpOne = () => import('../..\\components\\sections\\CounterUpOne.vue' /* webpackChunkName: "components/sections-counter-up-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsCounterUpTwo = () => import('../..\\components\\sections\\CounterUpTwo.vue' /* webpackChunkName: "components/sections-counter-up-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsFeaturesOne = () => import('../..\\components\\sections\\FeaturesOne.vue' /* webpackChunkName: "components/sections-features-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsFeatureStartUp = () => import('../..\\components\\sections\\FeatureStartUp.vue' /* webpackChunkName: "components/sections-feature-start-up" */).then(c => wrapFunctional(c.default || c))
export const SectionsOurServiceOne = () => import('../..\\components\\sections\\OurServiceOne.vue' /* webpackChunkName: "components/sections-our-service-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsPortfolioItemFilter = () => import('../..\\components\\sections\\PortfolioItemFilter.vue' /* webpackChunkName: "components/sections-portfolio-item-filter" */).then(c => wrapFunctional(c.default || c))
export const SectionsPortfolioOne = () => import('../..\\components\\sections\\PortfolioOne.vue' /* webpackChunkName: "components/sections-portfolio-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsPortfolioTwo = () => import('../..\\components\\sections\\PortfolioTwo.vue' /* webpackChunkName: "components/sections-portfolio-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsPricingOne = () => import('../..\\components\\sections\\PricingOne.vue' /* webpackChunkName: "components/sections-pricing-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceCarousel = () => import('../..\\components\\sections\\ServiceCarousel.vue' /* webpackChunkName: "components/sections-service-carousel" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceIconBoxOne = () => import('../..\\components\\sections\\ServiceIconBoxOne.vue' /* webpackChunkName: "components/sections-service-icon-box-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceIconBoxTwo = () => import('../..\\components\\sections\\ServiceIconBoxTwo.vue' /* webpackChunkName: "components/sections-service-icon-box-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceIconBoxWithTitle = () => import('../..\\components\\sections\\ServiceIconBoxWithTitle.vue' /* webpackChunkName: "components/sections-service-icon-box-with-title" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceIconBoxWithTitleStleTwo = () => import('../..\\components\\sections\\ServiceIconBoxWithTitleStleTwo.vue' /* webpackChunkName: "components/sections-service-icon-box-with-title-stle-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceOne = () => import('../..\\components\\sections\\ServiceOne.vue' /* webpackChunkName: "components/sections-service-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsServiceTwo = () => import('../..\\components\\sections\\ServiceTwo.vue' /* webpackChunkName: "components/sections-service-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsStartUpStratagy = () => import('../..\\components\\sections\\StartUpStratagy.vue' /* webpackChunkName: "components/sections-start-up-stratagy" */).then(c => wrapFunctional(c.default || c))
export const SectionsTeamFour = () => import('../..\\components\\sections\\TeamFour.vue' /* webpackChunkName: "components/sections-team-four" */).then(c => wrapFunctional(c.default || c))
export const SectionsTeamOne = () => import('../..\\components\\sections\\TeamOne.vue' /* webpackChunkName: "components/sections-team-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsTeamThree = () => import('../..\\components\\sections\\TeamThree.vue' /* webpackChunkName: "components/sections-team-three" */).then(c => wrapFunctional(c.default || c))
export const SectionsTeamTwo = () => import('../..\\components\\sections\\TeamTwo.vue' /* webpackChunkName: "components/sections-team-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialFive = () => import('../..\\components\\sections\\TestimonialFive.vue' /* webpackChunkName: "components/sections-testimonial-five" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialFour = () => import('../..\\components\\sections\\TestimonialFour.vue' /* webpackChunkName: "components/sections-testimonial-four" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialOne = () => import('../..\\components\\sections\\TestimonialOne.vue' /* webpackChunkName: "components/sections-testimonial-one" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialThree = () => import('../..\\components\\sections\\TestimonialThree.vue' /* webpackChunkName: "components/sections-testimonial-three" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialTwo = () => import('../..\\components\\sections\\TestimonialTwo.vue' /* webpackChunkName: "components/sections-testimonial-two" */).then(c => wrapFunctional(c.default || c))
export const SectionsTestimonialWithoutCarousel = () => import('../..\\components\\sections\\TestimonialWithoutCarousel.vue' /* webpackChunkName: "components/sections-testimonial-without-carousel" */).then(c => wrapFunctional(c.default || c))
export const SectionsWhatWeDoThree = () => import('../..\\components\\sections\\WhatWeDoThree.vue' /* webpackChunkName: "components/sections-what-we-do-three" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
